version: '3.9'

services:
  mongo:
    image: mongo:7.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - portfolio-network

  backend:
    build: ./server
    container_name: portfolio-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/portfolioDB
    depends_on:
      - mongo
    networks:
      - portfolio-network

  frontend:
    build: ./client
    container_name: portfolio-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - portfolio-network

  seeder:
    build:
      context: ./server
    container_name: portfolio-seeder
    command: ["npm", "run", "seed:all"]
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/portfolioDB
    networks:
      - portfolio-network
    restart: "no" # Optional: don’t restart once done

volumes:
  mongo-data:

networks:
  portfolio-network:
    driver: bridge
